//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR_ApartmentBase.Model.DB.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_nn_Category_Parameters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_nn_Category_Parameters()
        {
            this.F_nn_ElementInFlatValue = new HashSet<F_nn_ElementInFlatValue>();
            this.F_nn_ElementParam_Value = new HashSet<F_nn_ElementParam_Value>();
        }
    
        public int ID_CAT_PARAMETER { get; set; }
        public int ID_CATEGORY { get; set; }
        public int ID_PARAMETER { get; set; }
    
        public virtual F_S_Categories F_S_Categories { get; set; }
        public virtual F_S_Parameters F_S_Parameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_nn_ElementInFlatValue> F_nn_ElementInFlatValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_nn_ElementParam_Value> F_nn_ElementParam_Value { get; set; }
    }
}
