//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR_ApartmentBase.Model.DB.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_S_Elements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public F_S_Elements()
        {
            this.F_nn_Elements_FlatModules = new HashSet<F_nn_Elements_FlatModules>();
        }
    
        public int ID_ELEMENT { get; set; }
        public int ID_FAMILY_INFO { get; set; }
        public int ID_CATEGORY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<F_nn_Elements_FlatModules> F_nn_Elements_FlatModules { get; set; }
        public virtual F_S_Categories F_S_Categories { get; set; }
        public virtual F_S_FamilyInfos F_S_FamilyInfos { get; set; }
    }
}
